cc_binary(
    name = "calculator_with_side_packets",
    srcs = ["calculator_with_side_packets.cc", "goblin_calculator.cc"],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:logging",
        "//mediapipe/framework/port:status",
    ],
)
