# package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "custom_calculator",
    srcs = ["custom_calculator.cc"],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/port:logging",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
    ],
)
